---
- name: config vms
  hosts: all
  tasks:
    - name: ping - checking connection
      ansible.builtin.ping:

    - name: install node v14
      shell: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: install unzip
      shell:  sudo apt-get update && sudo apt install -y zip && sudo apt install -y unzip
